### ISSUE TITLE
Anonymous Support Form / Guest Users without the need to signup

### ISSUE THREAD

**Issue by mrandt** [smartcatdev/support-system#321]
I'd like to configure a support form which allows users to submit a ticket without signing up first.

It should be configurable in backend (which fields, layout, design, which default category to use, etc.) and possibly included anywhere on the public site, e.g. with a shortcode.

The logic to create guest users on the fly seems to be all available within e-mail piping add on.

I don't want to force my customers to create an account first, before they can submit a service request.

So far, my workaround has been a third-party e-mail form plugin which submits the request via e-mail piping, but that is limited in terms of functionality.

**Comment by smartcatdev** [comment]
Hi @mrandt 
I've had this request come up before, but the rationale behind not including a feature like this, is honestly i dont consider that a feature and here's my explanation:

1. your customers need to receive notifications. same as someone who registers. Therefore, ucare needs to know their email address, so that they can be notified the agent responds to their request. 

2. Customers need to go back into ucare to add a response. Therefore they need to login to the system in order to post responses. The system won't know who they are and will have no safe way of validating that the person who created the ticket can view/respond to it. So they need a username & password. 

lastly, in regards to forcing customers to sign up, this is not an issue for customers. We've used ucare to provide all our support for over a year, and not even a single complain about having to register. 

Registration is safer, more reliable, and guest tickets are just not a good idea, because they will force the system to have a huge workaround for very little, if any benefit.

Our email piping add-on has guest tickets, because it has to. Because customers emailing are un-known to the system when they send a first email. What uCare actually does in email piping is it auto-registers the customer, as a WP User of type guest. This is to ensure that all ucare standard functioanlity works the same way for email piping tickets and registered users.

**Comment by mrandt** [comment]
Thanks for the swift reply. I do understand your rationale but I kindly disagree.

I must have a means of contacting the user filing the request, but they don't necessarily need a login and password.

Actually, e-mail piping is the best demonstration of how this works. You create a guest user on the fly, assign him / her an e-mail address and one or multiple tickets. Whenever an agent replies, the guest user receives an e-mail with the "ticket reference" and if they reply back, their answer gets added to the ticket.

My "anonymous" form would work the same way. There is no need to go back into the portal and update info later, it can all be handled via e-mail for example. 

You could even go one step further and include a authentication key in the permalink for a ticket, so if a user clicked the "view my ticket online" link in an support e-mail, they would see the ticket in their browser and could reply directly. No password needed whatsoever...

I believe that the sign-in approach works well for your users, but you are supporting a digital product for mostly technical people, which is marketed and used on the Internet and for which the user needed to sign-up anyways just to obtain the product. 

Try supporting a physical product or a digital product that is on a different channel (like apps in my case) with less technical people - totally different story. Those users don't want another login just to submit a support request; in fact forcing them to remember yet another password will scare them away and leave you with negative feedback on the original channel.

Last point: Whenever a user creates a permanent account, you have to handle all issues of data protection and privacy laws - as you might know, GDPR is introducing massive legal changes in Europe and I'd like to avoid user accounts where I can.

**Comment by smartcatdev** [comment]
I see your point. From your perspective and use-case I see why it makes sense to have "guest" users. The thing is at the end of the day, guest users have to be WP users. So the idea makes sense, as long as the "guest" user level is still a WP user.

We'll have to think this through because Guest WP User will have unique exceptions for various things, and different use cases of the Guest account will require different behaviour. In your example, the customer you're supporting never has to login, however other users who've contacted us about guest users have had different scenarios. Some users requested a guest feature where the customer can go into the portal to view their tickets, which to me doesn't make sense. If someone signs up as a guest, it means they're not coming back, or if they come back, they won't have any history. But the requests we get for that don't agree with this.

Authenticating via auth key in the URL is a nice idea works for authentication, but doesn't work for retrieving ticket history, unless the user is a WP User. Because we're using WP, a ticket needs an author, which is an ID. so we need to reserve IDs in the DB to associate tickets with users. 

Other users wanted Guest Tickets because they're worried that the WP_User table size will be large. which is why email piping has the option to delete Guest users after X days.

**Comment by mrandt** [comment]
Thanks for your consideration.

I believe that - given the current implementation requires the customer to be the ticket author - you would still have to create WP users on the fly as with e-mail piping. These users don't have a password and thus cannot login directly.

Using auth keys in URLs you could still let a user see a ticket's history or update that ticket through an implicit login. However I would limit this to the current ticket.

I would keep an option to delete the guest user a couple days after the ticket has been resolved.
